package com.payments.system.container.model;

public enum EventType {
    PAYMENT_CREATED, PAYMENT_AUTHORIZED, PAYMENT_COMPLETED, PAYMENT_FAILED, REFUND_CREATED, REFUND_COMPLETED, REFUND_FAILED, SETTLEMENT_CREATED, SETTLEMENT_COMPLETED, NOTIFICATION_REQUESTED, NOTIFICATION_SENT, NOTIFICATION_FAILED
}
