package com.payments.basic.model;

public enum NotificationEventType {
    CHARGE_APPROVED, LARGE_TRANSACTION_ALERT, CHARGE_DECLINED, REFUND_PROCESSED, REFUND_FAILED, FRAUD_ALERT_RAISED, CARD_ADDED, CARD_EXPIRING_SOON, ACCOUNT_SUSPENDED, ACCOUNT_REACTIVATED
}
