spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://postgres:5432/payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false

  kafka:
    bootstrap-servers:
      - kafka:9092
    producer:
      acks: all
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 3
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.payments.system.container.model.PaymentCompletedEvent
#
#      listener:
#        ack-mode: manual
#       concurrency: 3

  threads:
    virtual:
      enabled: true

logging:
  level:
    root: info
